In [1]:
import pandas as pd
import numpy as np

In [2]:
caregiver_data = pd.read_csv('护工信息（筛选后）.csv', encoding='GBK')
caregiver_data

,护工ID,护工姓名,性别,生日,从业时间,服务商ID,所属服务商,评分（满分5分）,常驻医院,创建时间
0,478,史小平,女,1970/11/10,2010/12/31,1,宁波安欣陪护服务有限公司,4.6,宁波大学附属第一医院（外滩院区）,2023/5/14 23:22
1,1494,张清荣,女,1973/7/13,NaN,21,江苏美世界物业管理有限公司,4.9,宁波大学附属第一医院（方桥院区）,2023/9/1 16:21
2,1495,余世梅,女,1970/9/4,NaN,21,江苏美世界物业管理有限公司,4.5,宁波大学附属第一医院（方桥院区）,2023/9/1 16:21
3,1496,王正凡,男,1965/5/18,NaN,21,江苏美世界物业管理有限公司,5.0,宁波大学附属第一医院（方桥院区）,2023/9/1 16:21
4,1497,周新云,女,1966/11/13,NaN,21,江苏美世界物业管理有限公司,4.9,宁波大学附属第一医院（方桥院区）,2023/9/1 16:21
...,...,...,...,...,...,...,...,...,...,...
813,6310,潘升银,男,1974/2/19,NaN,45,上海智服人力资源有限公司,5.0,宁波大学附属第一医院（方桥院区）,2024/9/25 10:31
814,6311,黄秋香,女,1972/6/28,NaN,45,上海智服人力资源有限公司,4.7,宁波大学附属第一医院（方桥院区）,2024/9/25 10:40
815,6312,丁碧芳,女,NaN,NaN,21,江苏美世界物业管理有限公司,4.5,宁波大学附属第一医院（月湖院区）,2024/9/25 10:50
816,6332,贺昔妹,女,NaN,NaN,45,上海智服人力资源有限公司,NaN,宁波大学附属第一医院（方桥院区）,2024/9/27 8:34
817,6333,刘兆俊,女,1973/1/5,NaN,45,上海智服人力资源有限公司,NaN,宁波大学附属第一医院（方桥院区）,2024/9/27 8:36

In [3]:
caregiver_extend = pd.read_csv('护工扩展信息.csv')
caregiver_extend

,护工ID,护工名称,省,市,区,身高,体重,民族,宗教信仰,普通话程度,方言,方言程度,擅长科室,擅长病人,学历
0,1,崔宝英,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,李四妮,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,李连叶,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,林水飞,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,石芳秀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3860,6324,丁叶华,NaN,NaN,NaN,NaN,NaN,汉族,无宗教信仰,能听懂能交流,宁波话,能听懂能交流,不限,不限,NaN
3861,6325,杨克华,NaN,NaN,NaN,NaN,NaN,汉族,无宗教信仰,能听懂能交流,宁波话,能听懂能交流,不限,不限,NaN
3862,6331,dd,NaN,NaN,NaN,NaN,NaN,汉族,无宗教信仰,能听懂能交流,宁波话,能听懂能交流,不限,不限,NaN
3863,6332,贺昔妹,NaN,NaN,NaN,NaN,NaN,汉族,无宗教信仰,能听懂能交流,宁波话,能听懂能交流,不限,不限,NaN
3864,6333,刘兆俊,NaN,NaN,NaN,NaN,NaN,汉族,无宗教信仰,能听懂能交流,宁波话,能听懂能交流,不限,不限,NaN

In [4]:
extend_columns = list(caregiver_extend.columns)[2:]

In [5]:
for col in extend_columns:
    tmp = []
    for i in range(caregiver_data.shape[0]):
        ID = caregiver_data.iloc[i]['护工ID']
        target = caregiver_extend[caregiver_extend['护工ID'] == ID]
        if target.shape[0] > 0:
            tmp.append(caregiver_extend[caregiver_extend['护工ID'] == ID][col].iloc[0])
        else:
            tmp.append(np.nan)
    caregiver_data[col] = tmp

caregiver_data

,护工ID,护工姓名,性别,生日,从业时间,服务商ID,所属服务商,评分（满分5分）,常驻医院,创建时间,...,身高,体重,民族,宗教信仰,普通话程度,方言,方言程度,擅长科室,擅长病人,学历
0,478,史小平,女,1970/11/10,2010/12/31,1,宁波安欣陪护服务有限公司,4.6,宁波大学附属第一医院（外滩院区）,2023/5/14 23:22,...,159.0,58.0,汉族,无宗教信仰,能听懂能交流,宁波话,能听懂,消化科,消化科病人,初中
1,1494,张清荣,女,1973/7/13,NaN,21,江苏美世界物业管理有限公司,4.9,宁波大学附属第一医院（方桥院区）,2023/9/1 16:21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1495,余世梅,女,1970/9/4,NaN,21,江苏美世界物业管理有限公司,4.5,宁波大学附属第一医院（方桥院区）,2023/9/1 16:21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1496,王正凡,男,1965/5/18,NaN,21,江苏美世界物业管理有限公司,5.0,宁波大学附属第一医院（方桥院区）,2023/9/1 16:21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1497,周新云,女,1966/11/13,NaN,21,江苏美世界物业管理有限公司,4.9,宁波大学附属第一医院（方桥院区）,2023/9/1 16:21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,6310,潘升银,男,1974/2/19,NaN,45,上海智服人力资源有限公司,5.0,宁波大学附属第一医院（方桥院区）,2024/9/25 10:31,...,NaN,NaN,汉族,无宗教信仰,能听懂能交流,宁波话,能听懂能交流,不限,不限,NaN
814,6311,黄秋香,女,1972/6/28,NaN,45,上海智服人力资源有限公司,4.7,宁波大学附属第一医院（方桥院区）,2024/9/25 10:40,...,NaN,NaN,汉族,无宗教信仰,能听懂能交流,宁波话,能听懂能交流,不限,不限,NaN
815,6312,丁碧芳,女,NaN,NaN,21,江苏美世界物业管理有限公司,4.5,宁波大学附属第一医院（月湖院区）,2024/9/25 10:50,...,NaN,NaN,汉族,无宗教信仰,能听懂能交流,宁波话,能听懂能交流,不限,不限,NaN
816,6332,贺昔妹,女,NaN,NaN,45,上海智服人力资源有限公司,NaN,宁波大学附属第一医院（方桥院区）,2024/9/27 8:34,...,NaN,NaN,汉族,无宗教信仰,能听懂能交流,宁波话,能听懂能交流,不限,不限,NaN
817,6333,刘兆俊,女,1973/1/5,NaN,45,上海智服人力资源有限公司,NaN,宁波大学附属第一医院（方桥院区）,2024/9/27 8:36,...,NaN,NaN,汉族,无宗教信仰,能听懂能交流,宁波话,能听懂能交流,不限,不限,NaN

In [6]:
caregiver_certification = pd.read_csv('护工资质信息.csv', encoding='GBK')
caregiver_certification

    资质类型  护工ID             获取时间         认证单位             创建时间   资质名称
0    护理类    23  2023/5/31 14:02      宁波市第一医院   2023/7/3 14:02    NaN
1    操作类    23  2023/5/31 14:02      宁波市第一医院   2023/7/3 14:02    NaN
2    信息类  4181   2023/12/4 0:00      宁海县中医医院  2023/12/5 19:45    健康证
3    信息类  4181   2017/6/27 0:00       甘谷县公安局  2023/12/5 19:48    身份证
4    信息类  4181  2023/11/27 8:00  馨知爱护理服务有限公司  2023/12/5 19:50    上岗证
..   ...   ...              ...          ...              ...    ...
154  认证类  1261              NaN          NaN   2024/7/5 10:00  养老护理员
155  认证类  1284              NaN          NaN   2024/7/5 10:28    保育师
156  认证类  1277              NaN          NaN  2024/7/10 10:28  养老护理员
157  认证类  1229              NaN          NaN  2024/7/10 14:58  养老护理员
158  认证类  4447              NaN          NaN  2024/7/15 15:55  养老护理员

[159 rows x 6 columns]

In [7]:
cnt = 0
for i in range(caregiver_data.shape[0]):
    ID = caregiver_data.iloc[i]['护工ID']
    target = caregiver_certification[caregiver_certification['护工ID'] == ID]
    if target.shape[0] > 0:
        print(target)
        cnt += 1
print(cnt)

    资质类型  护工ID           获取时间               认证单位             创建时间         资质名称
150  操作类   478  2024/6/7 0:00  浙江省卫生行业职业技能鉴定指导中心  2024/6/21 12:47  医疗护理员操作技能证书
151  信息类   478  2024/3/9 0:00                NaN  2024/6/21 13:06          健康证
1

In [8]:
caregiver_data.isnull().sum()

护工ID          0
护工姓名          0
性别            0
生日          257
从业时间        796
服务商ID         0
所属服务商         0
评分（满分5分）     10
常驻医院          0
创建时间          0
省           781
市           798
区           818
身高          811
体重          816
民族          500
宗教信仰        500
普通话程度       500
方言          500
方言程度        500
擅长科室        500
擅长病人        500
学历          799
dtype: int64