In [1]:
import pandas as pd

In [2]:
caregiver_data = pd.read_csv('护工信息.csv', encoding='GBK')
caregiver_data

,护工ID,护工姓名,性别,生日,从业时间,服务商ID,所属服务商,评分（满分5分）,常驻医院,创建时间
0,1,崔宝英,女,NaN,1900/1/2,6,宁波市江东欣和陪护服务有限公司（中西医结合医院服务部）,NaN,NaN,2023/5/14 23:22
1,2,李四妮,女,NaN,1900/1/2,6,宁波市江东欣和陪护服务有限公司（中西医结合医院服务部）,NaN,NaN,2023/5/14 23:22
2,3,李连叶,女,NaN,1900/1/2,8,宁波市江东欣和陪护服务有限公司（明州医院服务部）,NaN,NaN,2023/5/14 23:22
3,4,林水飞,女,NaN,1900/1/2,8,宁波市江东欣和陪护服务有限公司（明州医院服务部）,NaN,NaN,2023/5/14 23:22
4,5,石芳秀,女,NaN,1900/1/2,8,宁波市江东欣和陪护服务有限公司（明州医院服务部）,NaN,NaN,2023/5/14 23:22
...,...,...,...,...,...,...,...,...,...,...
5987,6329,屠爱红,女,1958/9/14,NaN,28,浙江盛元城市物业管理有限公司古塘分公司,4.9,NaN,2024/9/26 14:31
5988,6330,陈胜霞,女,1975/6/5,NaN,28,浙江盛元城市物业管理有限公司古塘分公司,5.0,NaN,2024/9/26 14:31
5989,6331,dd,男,NaN,NaN,47,甬联-转运,NaN,NaN,2024/9/26 14:31
5990,6332,贺昔妹,女,NaN,NaN,45,上海智服人力资源有限公司,NaN,宁波大学附属第一医院(方桥院区),2024/9/27 8:34
5991,6333,刘兆俊,女,1973/1/5,NaN,45,上海智服人力资源有限公司,NaN,宁波大学附属第一医院(方桥院区),2024/9/27 8:36

In [3]:
# 去除“常驻医院”信息缺失的护工
caregiver_data_cleaned = caregiver_data.dropna(subset=['常驻医院'])
caregiver_data_cleaned

,护工ID,护工姓名,性别,生日,从业时间,服务商ID,所属服务商,评分（满分5分）,常驻医院,创建时间
22,23,刘纪芳,女,1971/5/17,1900/1/2,15,小柏家护,4.6,宁波市医疗中心李惠利医院（兴宁院区）,2023/5/14 23:22
388,389,王爱莲,女,1965/2/23,1900/1/2,15,小柏家护,4.5,宁波市医疗中心李惠利医院（兴宁院区）,2023/5/14 23:22
406,407,梁本娟,女,1964/8/27,1900/1/2,15,小柏家护,4.6,宁波市医疗中心李惠利医院（兴宁院区）,2023/5/14 23:22
407,408,丁翠燕,女,1969/3/15,1900/1/2,15,小柏家护,5.0,宁波市医疗中心李惠利医院（兴宁院区）,2023/5/14 23:22
408,409,吴相陆,女,1969/2/6,1900/1/2,15,小柏家护,4.8,宁波市医疗中心李惠利医院（兴宁院区）,2023/5/14 23:22
...,...,...,...,...,...,...,...,...,...,...
5971,6313,张飞,男,1975/2/12,NaN,34,余姚市康复家政服务有限公司,4.6,余姚市第三人民医院,2024/9/25 16:37
5972,6314,张飞,男,1975/2/12,NaN,34,余姚市康复家政服务有限公司,4.5,余姚市第三人民医院,2024/9/25 16:37
5974,6316,史光珍,女,NaN,NaN,2,宁波市乐乐园家政服务有限公司,4.8,宁波市医疗中心李惠利医院(兴宁院区),2024/9/26 9:50
5990,6332,贺昔妹,女,NaN,NaN,45,上海智服人力资源有限公司,NaN,宁波大学附属第一医院(方桥院区),2024/9/27 8:34
5991,6333,刘兆俊,女,1973/1/5,NaN,45,上海智服人力资源有限公司,NaN,宁波大学附属第一医院(方桥院区),2024/9/27 8:36

In [4]:
# 筛选出“常驻医院”为宁波大学附属第一医院的护工
caregiver_data_hospital_1 = caregiver_data_cleaned[caregiver_data_cleaned['常驻医院'].str.contains('宁波大学附属第一医院')]
caregiver_data_hospital_1

,护工ID,护工姓名,性别,生日,从业时间,服务商ID,所属服务商,评分（满分5分）,常驻医院,创建时间
477,478,史小平,女,1970/11/10,2010/12/31,1,宁波安欣陪护服务有限公司,4.6,宁波大学附属第一医院(外滩院区),2023/5/14 23:22
1152,1494,张清荣,女,1973/7/13,NaN,21,江苏美世界物业管理有限公司,4.9,宁波大学附属第一医院（方桥院区）,2023/9/1 16:21
1153,1495,余世梅,女,1970/9/4,NaN,21,江苏美世界物业管理有限公司,4.5,宁波大学附属第一医院（方桥院区）,2023/9/1 16:21
1154,1496,王正凡,男,1965/5/18,NaN,21,江苏美世界物业管理有限公司,5.0,宁波大学附属第一医院（方桥院区）,2023/9/1 16:21
1155,1497,周新云,女,1966/11/13,NaN,21,江苏美世界物业管理有限公司,4.9,宁波大学附属第一医院（方桥院区）,2023/9/1 16:21
...,...,...,...,...,...,...,...,...,...,...
5968,6310,潘升银,男,1974/2/19,NaN,45,上海智服人力资源有限公司,5.0,宁波大学附属第一医院(方桥院区),2024/9/25 10:31
5969,6311,黄秋香,女,1972/6/28,NaN,45,上海智服人力资源有限公司,4.7,宁波大学附属第一医院(方桥院区),2024/9/25 10:40
5970,6312,丁碧芳,女,NaN,NaN,21,江苏美世界物业管理有限公司,4.5,宁波大学附属第一医院(月湖院区),2024/9/25 10:50
5990,6332,贺昔妹,女,NaN,NaN,45,上海智服人力资源有限公司,NaN,宁波大学附属第一医院(方桥院区),2024/9/27 8:34
5991,6333,刘兆俊,女,1973/1/5,NaN,45,上海智服人力资源有限公司,NaN,宁波大学附属第一医院(方桥院区),2024/9/27 8:36

In [5]:
# 统一“常驻医院”中文小括号为英文小括号
caregiver_data_hospital_1_cleaned = caregiver_data_hospital_1.copy()
caregiver_data_hospital_1_cleaned['常驻医院'] = caregiver_data_hospital_1_cleaned['常驻医院'].str.replace('(', '（').str.replace(')', '）')

caregiver_data_hospital_1_cleaned

C:\Users\echo_\AppData\Local\Temp\ipykernel_37108\805406148.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  caregiver_data_hospital_1_cleaned['常驻医院'] = caregiver_data_hospital_1_cleaned['常驻医院'].str.replace('(', '（').str.replace(')', '）')

,护工ID,护工姓名,性别,生日,从业时间,服务商ID,所属服务商,评分（满分5分）,常驻医院,创建时间
477,478,史小平,女,1970/11/10,2010/12/31,1,宁波安欣陪护服务有限公司,4.6,宁波大学附属第一医院（外滩院区）,2023/5/14 23:22
1152,1494,张清荣,女,1973/7/13,NaN,21,江苏美世界物业管理有限公司,4.9,宁波大学附属第一医院（方桥院区）,2023/9/1 16:21
1153,1495,余世梅,女,1970/9/4,NaN,21,江苏美世界物业管理有限公司,4.5,宁波大学附属第一医院（方桥院区）,2023/9/1 16:21
1154,1496,王正凡,男,1965/5/18,NaN,21,江苏美世界物业管理有限公司,5.0,宁波大学附属第一医院（方桥院区）,2023/9/1 16:21
1155,1497,周新云,女,1966/11/13,NaN,21,江苏美世界物业管理有限公司,4.9,宁波大学附属第一医院（方桥院区）,2023/9/1 16:21
...,...,...,...,...,...,...,...,...,...,...
5968,6310,潘升银,男,1974/2/19,NaN,45,上海智服人力资源有限公司,5.0,宁波大学附属第一医院（方桥院区）,2024/9/25 10:31
5969,6311,黄秋香,女,1972/6/28,NaN,45,上海智服人力资源有限公司,4.7,宁波大学附属第一医院（方桥院区）,2024/9/25 10:40
5970,6312,丁碧芳,女,NaN,NaN,21,江苏美世界物业管理有限公司,4.5,宁波大学附属第一医院（月湖院区）,2024/9/25 10:50
5990,6332,贺昔妹,女,NaN,NaN,45,上海智服人力资源有限公司,NaN,宁波大学附属第一医院（方桥院区）,2024/9/27 8:34
5991,6333,刘兆俊,女,1973/1/5,NaN,45,上海智服人力资源有限公司,NaN,宁波大学附属第一医院（方桥院区）,2024/9/27 8:36

In [23]:
caregiver_data_hospital_1_cleaned.to_csv('护工信息（筛选后）.csv', index=False)