In [1]:
import pandas as pd

In [2]:
order_data = pd.read_csv('原数据/订单信息.csv', encoding='GBK')
order_data

,订单号,费用（单位分）,已支付费用,已退款费用,持续时间（单位天）,医院ID,医院名称,病区ID,病区名称,床位号,...,服务商ID,服务商名称,患者年龄,患者性别,护工ID,护工名称,订单类型,接单时间,关闭时间,创建时间
0,1.678190e+18,384000,0,0,16,9,宁波市第六医院,262,3号楼 6楼,NaN,...,7,宁波市江东欣和陪护服务有限公司（第六医院服务部）,48.0,未知,NaN,NaN,一对一,NaN,2023/7/10 7:53,2023/7/10 7:46
1,1.677960e+18,40000,0,0,2,1,宁波大学附属人民医院,2,F11 妇科一,NaN,...,15,小柏家护,52.0,未知,679.0,潘元伢,一对一,NaN,2023/7/14 13:41,2023/7/9 16:25
2,1.677880e+18,23000,0,0,1,8,宁波市第二医院,235,北院区 8F,NaN,...,15,小柏家护,42.0,未知,135.0,王双华,一对一,NaN,2023/7/14 10:23,2023/7/9 11:33
3,1.677200e+18,23000,0,0,1,8,宁波市第二医院,222,8号楼 Ⅱ期5F,NaN,...,15,小柏家护,70.0,未知,332.0,杨银庭,一对一,NaN,2023/7/8 7:12,2023/7/7 14:23
4,1.677120e+18,22000,0,0,1,3,宁波大学附属第一医院（月湖院区）,275,2号楼 11楼,NaN,...,15,小柏家护,67.0,未知,NaN,NaN,一对一,NaN,2023/7/8 8:31,2023/7/7 8:39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41030,1.800000e+17,0,0,0,0,19,宁波市北仑区第二人民医院,464,住院部 4F,30,...,5,宁波市开米家庭服务有限公司,59.0,女,NaN,NaN,一对一,NaN,NaN,2024/9/27 10:37
41031,1.800000e+17,0,0,0,0,5,宁波市医疗中心李惠利医院(东部院区),241,住院部急诊抢救室,16,...,5,宁波市开米家庭服务有限公司,76.0,女,NaN,NaN,一对一,NaN,NaN,2024/9/27 10:37
41032,1.800000e+17,0,0,0,0,2,宁波大学附属第一医院(外滩院区),30,1号楼 10楼,10,...,15,小柏家护,56.0,女,NaN,NaN,一对一,NaN,NaN,2024/9/27 10:38
41033,1.800000e+17,0,0,0,0,2,宁波大学附属第一医院(外滩院区),47,绣山医学楼 10楼,21,...,1,宁波安欣陪护服务有限公司,81.0,男,NaN,NaN,一对一,NaN,NaN,2024/9/27 10:39
41034,1.800000e+17,0,0,0,0,2,宁波大学附属第一医院(外滩院区),37,1号楼 16楼,32,...,15,小柏家护,69.0,女,NaN,NaN,一对一,NaN,NaN,2024/9/27 10:39

In [3]:
order_data_hospital_1 = order_data[order_data['医院名称'].str.contains('宁波大学附属第一医院')]
order_data_hospital_1

,订单号,费用（单位分）,已支付费用,已退款费用,持续时间（单位天）,医院ID,医院名称,病区ID,病区名称,床位号,...,服务商ID,服务商名称,患者年龄,患者性别,护工ID,护工名称,订单类型,接单时间,关闭时间,创建时间
4,1.677120e+18,22000,0,0,1,3,宁波大学附属第一医院（月湖院区）,275,2号楼 11楼,NaN,...,15,小柏家护,67.0,未知,NaN,NaN,一对一,NaN,2023/7/8 8:31,2023/7/7 8:39
9,1.675640e+18,52000,0,0,2,2,宁波大学附属第一医院（外滩院区）,52,绣山医学楼 14F肿瘤血液科,NaN,...,1,宁波安欣陪护服务有限公司（第一医院服务部）,62.0,未知,NaN,NaN,一对一,NaN,2023/7/3 13:14,2023/7/3 7:00
10,1.675340e+18,96000,0,0,4,2,宁波大学附属第一医院（外滩院区）,53,绣山医学楼 15F呼吸与危重症医学科,NaN,...,1,宁波安欣陪护服务有限公司（第一医院服务部）,68.0,未知,NaN,NaN,一对一,NaN,2023/7/2 15:44,2023/7/2 11:01
32,1.670000e+18,115000,0,0,5,3,宁波大学附属第一医院（月湖院区）,300,3号楼 8楼东,NaN,...,15,小柏家护,NaN,未知,NaN,NaN,一对一,NaN,2023/6/26 9:10,2023/6/26 9:06
39,1.670000e+18,92000,0,0,4,3,宁波大学附属第一医院（月湖院区）,287,2号楼 23楼,NaN,...,15,小柏家护,64.0,女,NaN,NaN,一对一,NaN,2023/6/17 17:06,2023/6/17 16:58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41028,1.800000e+17,50000,50000,0,2,2,宁波大学附属第一医院(外滩院区),33,1号楼 12楼,17,...,15,小柏家护,33.0,女,1905.0,马献芬,一对一,2024/9/27 10:36,NaN,2024/9/27 10:35
41029,1.800000e+17,50000,50000,0,2,2,宁波大学附属第一医院(外滩院区),40,1号楼 19楼,32,...,15,小柏家护,83.0,女,344.0,李卯香,一对一,2024/9/27 10:36,NaN,2024/9/27 10:35
41032,1.800000e+17,0,0,0,0,2,宁波大学附属第一医院(外滩院区),30,1号楼 10楼,10,...,15,小柏家护,56.0,女,NaN,NaN,一对一,NaN,NaN,2024/9/27 10:38
41033,1.800000e+17,0,0,0,0,2,宁波大学附属第一医院(外滩院区),47,绣山医学楼 10楼,21,...,1,宁波安欣陪护服务有限公司,81.0,男,NaN,NaN,一对一,NaN,NaN,2024/9/27 10:39
41034,1.800000e+17,0,0,0,0,2,宁波大学附属第一医院(外滩院区),37,1号楼 16楼,32,...,15,小柏家护,69.0,女,NaN,NaN,一对一,NaN,NaN,2024/9/27 10:39

In [4]:
order_data_hospital_1_cleaned = order_data_hospital_1.copy()

# 统一“医院名称”字段
order_data_hospital_1_cleaned['医院名称'] = order_data_hospital_1_cleaned['医院名称'].str.replace('(', '（').str.replace(')', '）')
# 删除“护工ID”为空的记录
order_data_hospital_1_cleaned = order_data_hospital_1_cleaned.dropna(subset=['护工ID'])

order_data_hospital_1_cleaned['患者年龄'] = order_data_hospital_1_cleaned['患者年龄'].astype(int)
order_data_hospital_1_cleaned['护工ID'] = order_data_hospital_1_cleaned['护工ID'].astype(int)

order_data_hospital_1_cleaned

C:\Users\echo_\AppData\Local\Temp\ipykernel_17632\3877111307.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  order_data_hospital_1_cleaned['医院名称'] = order_data_hospital_1_cleaned['医院名称'].str.replace('(', '（').str.replace(')', '）')

,订单号,费用（单位分）,已支付费用,已退款费用,持续时间（单位天）,医院ID,医院名称,病区ID,病区名称,床位号,...,服务商ID,服务商名称,患者年龄,患者性别,护工ID,护工名称,订单类型,接单时间,关闭时间,创建时间
120,1.660000e+18,44000,0,0,2,3,宁波大学附属第一医院（月湖院区）,287,2号楼 23楼,NaN,...,15,小柏家护,71,未知,75,罗红燕,一对一,NaN,2023/12/12 17:52,2023/5/23 11:38
134,1.660000e+18,84000,0,0,3,2,宁波大学附属第一医院（外滩院区）,61,绣山医学楼 7F消化中心(消化内科),NaN,...,1,宁波安欣陪护服务有限公司（第一医院服务部）,67,未知,484,李卫红,一对一,NaN,2023/5/20 0:42,2023/5/18 9:14
136,1.660000e+18,56000,0,0,2,2,宁波大学附属第一医院（外滩院区）,61,绣山医学楼 7F消化中心(消化内科),NaN,...,1,宁波安欣陪护服务有限公司（第一医院服务部）,67,未知,471,李五妮,一对一,NaN,2023/5/17 22:18,2023/5/17 22:13
137,1.660000e+18,84000,0,0,3,2,宁波大学附属第一医院（外滩院区）,61,绣山医学楼 7F消化中心(消化内科),NaN,...,1,宁波安欣陪护服务有限公司（第一医院服务部）,67,未知,485,孙艳华,一对一,NaN,2023/5/17 22:07,2023/5/17 22:07
138,1.660000e+18,56000,0,0,2,2,宁波大学附属第一医院（外滩院区）,61,绣山医学楼 7F消化中心(消化内科),NaN,...,1,宁波安欣陪护服务有限公司（第一医院服务部）,28,未知,491,李天佑,一对一,NaN,2023/5/17 22:00,2023/5/17 21:59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40952,1.790000e+17,60000,60000,0,2,2,宁波大学附属第一医院（外滩院区）,44,1号楼 7楼,21,...,1,宁波安欣陪护服务有限公司,36,男,2123,牛小玲,一对一,2024/9/26 16:08,NaN,2024/9/26 16:07
40954,1.790000e+17,50000,50000,0,2,16,宁波大学附属第一医院（方桥院区）,371,6号楼 6楼,1,...,45,上海智服人力资源有限公司,62,男,6332,贺昔妹,一对一,2024/9/26 16:48,NaN,2024/9/26 16:40
40964,1.790000e+17,125000,0,0,5,3,宁波大学附属第一医院（月湖院区）,306,5号楼 9楼,32,...,21,江苏美世界物业管理有限公司,67,男,1599,黄玉枝,一对一,2024/9/26 19:52,NaN,2024/9/26 19:39
41028,1.800000e+17,50000,50000,0,2,2,宁波大学附属第一医院（外滩院区）,33,1号楼 12楼,17,...,15,小柏家护,33,女,1905,马献芬,一对一,2024/9/27 10:36,NaN,2024/9/27 10:35
41029,1.800000e+17,50000,50000,0,2,2,宁波大学附属第一医院（外滩院区）,40,1号楼 19楼,32,...,15,小柏家护,83,女,344,李卯香,一对一,2024/9/27 10:36,NaN,2024/9/27 10:35

In [13]:
# 异常值检测
order_data_hospital_1_cleaned[order_data_hospital_1_cleaned['患者年龄'] < 0]

,订单号,费用（单位分）,已支付费用,已退款费用,持续时间（单位天）,医院ID,医院名称,病区ID,病区名称,床位号,...,服务商ID,服务商名称,患者年龄,患者性别,护工ID,护工名称,订单类型,接单时间,关闭时间,创建时间
1179,4.200000e+16,48000,0,0,2,16,宁波大学附属第一医院（方桥院区）,365,7号楼 11楼,16,...,21,江苏美世界物业管理有限公司,-5,女,1535,孙玉华,一对一,NaN,2023/12/12 17:52,2023/9/13 13:35

In [14]:
# 异常值检测
order_data_hospital_1_cleaned[order_data_hospital_1_cleaned['患者年龄'] > 104]

,订单号,费用（单位分）,已支付费用,已退款费用,持续时间（单位天）,医院ID,医院名称,病区ID,病区名称,床位号,...,服务商ID,服务商名称,患者年龄,患者性别,护工ID,护工名称,订单类型,接单时间,关闭时间,创建时间
1279,4.270000e+16,72000,0,0,3,2,宁波大学附属第一医院（外滩院区）,52,绣山医学楼 14楼,R1,...,1,宁波安欣陪护服务有限公司,1963,男,1730,钱燃英,一对一,NaN,2023/12/12 17:52,2023/9/15 11:01
13108,9.960000e+16,250000,0,0,10,3,宁波大学附属第一医院（月湖院区）,277,2号楼 13楼,22,...,21,江苏美世界物业管理有限公司,822,男,1584,谷金华,一对一,NaN,2024/3/7 1:00,2024/2/19 12:22
23838,1.300000e+17,48000,0,0,2,3,宁波大学附属第一医院（月湖院区）,275,2号楼 11楼,2号5床,...,21,江苏美世界物业管理有限公司,1950,女,1641,王爱平,一对一,2024/5/13 14:13,2024/5/22 1:00,2024/5/13 12:38
28023,1.420000e+17,60000,0,0,2,2,宁波大学附属第一医院（外滩院区）,45,1号楼 8楼,4,...,1,宁波安欣陪护服务有限公司,1987,女,4946,史玉燕,一对一,2024/6/14 15:30,2024/6/23 1:00,2024/6/14 15:29

In [5]:
order_data_hospital_1_cleaned.to_csv('订单信息（清洗后）_1.csv', index=False)