In [1]:
import pandas as pd

In [2]:
nurseData = pd.read_csv('normalized_nurseData.csv')
nurseData

,护工ID,护工姓名,性别,年龄,省,民族,宗教信仰,学历,普通话程度,方言程度,...,在岗时间,擅长科室,擅长科室种类,接单数,活跃度,评分,所属服务商,常驻医院,主要负责病区,其他负责病区
0,1641,王爱平,0,0.561224,2,33,43,49,1,0,...,0.780876,急诊科、泌尿科,0.50,0.153846,0.029762,0.4,JSMSJ,59,62,67
1,1725,孙桂梅,0,0.591837,2,33,43,50,2,2,...,0.772908,无,0.00,0.000000,0.011905,1.0,NBAX,60,63,74
2,1873,陈均妃,0,0.489796,2,33,43,49,1,1,...,0.741036,泌尿科,0.25,0.076923,0.011905,0.4,JSMSJ,59,62,67
3,6195,李婷,0,0.479592,2,33,43,51,2,2,...,0.049801,无,0.00,0.076923,0.125000,1.0,NBAX,60,64,74
4,4450,董建敏,0,0.448980,3,33,43,49,1,2,...,0.521912,无,0.00,0.000000,0.005952,0.4,NBAX,60,63,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,5461,邹生凤,0,0.540816,4,33,43,52,2,2,...,0.213147,无,0.00,0.000000,0.011905,0.8,JSMSJ,59,67,74
496,5074,王艳慧,0,0.387755,2,33,43,50,2,1,...,0.394422,无,0.00,0.769231,0.125000,0.2,NBAX,60,64,63
497,1518,徐月仙,0,0.602041,2,33,43,49,1,1,...,0.780876,无,0.00,0.000000,0.005952,0.4,JSMSJ,61,65,74
498,5499,张红英,0,0.510204,2,33,43,51,1,0,...,0.199203,无,0.00,0.153846,0.095238,0.0,SHZF,61,66,74
499,1506,贺远娥,0,0.510204,2,33,43,51,1,0,...,0.780876,无,0.00,0.307692,0.023810,0.4,JSMSJ,61,65,70

In [3]:
tmp = {}
tokenId = 0

for col in ['擅长科室', '所属服务商']:
    for token in nurseData[col].unique().tolist():
        if token not in tmp.keys():
            tmp[token] = tokenId
            tokenId += 1

for i, row in nurseData.iterrows():
    for col in ['擅长科室', '所属服务商']:
        nurseData.loc[i, col] = tmp[row[col]]

nurseData

,护工ID,护工姓名,性别,年龄,省,民族,宗教信仰,学历,普通话程度,方言程度,...,在岗时间,擅长科室,擅长科室种类,接单数,活跃度,评分,所属服务商,常驻医院,主要负责病区,其他负责病区
0,1641,王爱平,0,0.561224,2,33,43,49,1,0,...,0.780876,0,0.50,0.153846,0.029762,0.4,46,59,62,67
1,1725,孙桂梅,0,0.591837,2,33,43,50,2,2,...,0.772908,1,0.00,0.000000,0.011905,1.0,47,60,63,74
2,1873,陈均妃,0,0.489796,2,33,43,49,1,1,...,0.741036,2,0.25,0.076923,0.011905,0.4,46,59,62,67
3,6195,李婷,0,0.479592,2,33,43,51,2,2,...,0.049801,1,0.00,0.076923,0.125000,1.0,47,60,64,74
4,4450,董建敏,0,0.448980,3,33,43,49,1,2,...,0.521912,1,0.00,0.000000,0.005952,0.4,47,60,63,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,5461,邹生凤,0,0.540816,4,33,43,52,2,2,...,0.213147,1,0.00,0.000000,0.011905,0.8,46,59,67,74
496,5074,王艳慧,0,0.387755,2,33,43,50,2,1,...,0.394422,1,0.00,0.769231,0.125000,0.2,47,60,64,63
497,1518,徐月仙,0,0.602041,2,33,43,49,1,1,...,0.780876,1,0.00,0.000000,0.005952,0.4,46,61,65,74
498,5499,张红英,0,0.510204,2,33,43,51,1,0,...,0.199203,1,0.00,0.153846,0.095238,0.0,48,61,66,74
499,1506,贺远娥,0,0.510204,2,33,43,51,1,0,...,0.780876,1,0.00,0.307692,0.023810,0.4,46,61,65,70

In [4]:
min2Max = {}
columns = ['性别', '省', '民族', '宗教信仰', '学历', '普通话程度', '方言程度', '体型', '擅长科室', '所属服务商', '常驻医院', '主要负责病区', '其他负责病区']

for col in columns:
    values = nurseData[col].tolist()
    minValue = min(values)
    maxValue = max(values)

    min2Max[col] = (minValue, maxValue)

for i, row in nurseData.iterrows():
    for col in columns:
        (minValue, maxValue) = min2Max[col]
        nurseData.loc[i, col] = (row[col] - minValue) / (maxValue - minValue)

nurseData

,护工ID,护工姓名,性别,年龄,省,民族,宗教信仰,学历,普通话程度,方言程度,...,在岗时间,擅长科室,擅长科室种类,接单数,活跃度,评分,所属服务商,常驻医院,主要负责病区,其他负责病区
0,1641,王爱平,0,0.561224,0.000000,0.0,0.0,0.000000,0,0.0,...,0.780876,0.0,0.50,0.153846,0.029762,0.4,0.0,0.0,0.0,0.416667
1,1725,孙桂梅,0,0.591837,0.000000,0.0,0.0,0.333333,1,1.0,...,0.772908,0.022222,0.00,0.000000,0.011905,1.0,0.5,0.5,0.1,1.000000
2,1873,陈均妃,0,0.489796,0.000000,0.0,0.0,0.000000,0,0.5,...,0.741036,0.044444,0.25,0.076923,0.011905,0.4,0.0,0.0,0.0,0.416667
3,6195,李婷,0,0.479592,0.000000,0.0,0.0,0.666667,1,1.0,...,0.049801,0.022222,0.00,0.076923,0.125000,1.0,0.5,0.5,0.2,1.000000
4,4450,董建敏,0,0.448980,0.071429,0.0,0.0,0.000000,0,1.0,...,0.521912,0.022222,0.00,0.000000,0.005952,0.4,0.5,0.5,0.1,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,5461,邹生凤,0,0.540816,0.142857,0.0,0.0,1.000000,1,1.0,...,0.213147,0.022222,0.00,0.000000,0.011905,0.8,0.0,0.0,0.5,1.000000
496,5074,王艳慧,0,0.387755,0.000000,0.0,0.0,0.333333,1,0.5,...,0.394422,0.022222,0.00,0.769231,0.125000,0.2,0.5,0.5,0.2,0.083333
497,1518,徐月仙,0,0.602041,0.000000,0.0,0.0,0.000000,0,0.5,...,0.780876,0.022222,0.00,0.000000,0.005952,0.4,0.0,1.0,0.3,1.000000
498,5499,张红英,0,0.510204,0.000000,0.0,0.0,0.666667,0,0.0,...,0.199203,0.022222,0.00,0.153846,0.095238,0.0,1.0,1.0,0.4,1.000000
499,1506,贺远娥,0,0.510204,0.000000,0.0,0.0,0.666667,0,0.0,...,0.780876,0.022222,0.00,0.307692,0.023810,0.4,0.0,1.0,0.3,0.666667

In [24]:
import numpy as np

def getSimilarity(list1, list2):
    return round(np.dot(list1, list2) / (np.linalg.norm(list1) * np.linalg.norm(list2)), 2)

In [15]:
# nurseCount = nurseData.shape[0]
nurseCount = 200

In [19]:
similarity_matrix = [[0] * nurseCount for _ in range(nurseCount)]
for i in range(nurseCount):
    for j in range(nurseCount):
        res = getSimilarity(nurseData.iloc[i][2:], nurseData.iloc[j][2:])
        if res >= 0.9:
            similarity_matrix[i][j] = res
np.array(similarity_matrix)

array([[1.  , 0.44, 0.79, ..., 0.36, 0.46, 0.58],
       [0.44, 1.  , 0.44, ..., 0.79, 0.78, 0.34],
       [0.79, 0.44, 1.  , ..., 0.42, 0.43, 0.74],
       ...,
       [0.36, 0.79, 0.42, ..., 1.  , 0.68, 0.32],
       [0.46, 0.78, 0.43, ..., 0.68, 1.  , 0.28],
       [0.58, 0.34, 0.74, ..., 0.32, 0.28, 1.  ]])

In [18]:
with open('simi_matrix_nurse.txt', 'w') as file:
    for i in range(nurseCount):
        similarity_info = ', '.join(map(str, similarity_matrix[i]))
        file.write(f'{i}: {similarity_info}\n')

10.213239266490127

In [20]:
k = 1
while k >= 0.8:
    edges = {}
    edgeCount = 0
    for i in range(nurseCount):
        tarList = []
        for j in range(nurseCount):
            if i != j:
                res = getSimilarity(nurseData.iloc[i][2:], nurseData.iloc[j][2:])
                if res >= k:
                    tarList.append(j)

        if len(tarList) > 0:
            edges[i] = tarList
            edgeCount += len(tarList)

    if edgeCount > 0:
        with open(f'edge/200_1000/edge_nurse_{round(k, 1)}.txt', 'w') as file:
            for i in range(nurseCount):
                if i in edges.keys():
                    edgeInfo = ', '.join(map(str, edges[i]))
                    file.write(f'{i}: {edgeInfo}\n')

            file.write(f'edgeCount: {edgeCount}\n')

    print(k, edgeCount)
    k -= 0.1

In [21]:
patientData = pd.read_csv('normalized_patientData.csv')
patientData

0.9 330
0.8 1462
0.7000000000000001 4216
0.6000000000000001 10682
0.5000000000000001 20220

In [25]:
min2Max = {}
columns = ['性别', '省', '民族', '宗教信仰', '学历', '体型', '过敏史', '是否残疾', '暴露史', '是否吸烟', '是否饮酒', '常饮酒类', '所属医院', '所在病区']

for col in columns:
    values = patientData[col].tolist()
    minValue = min(values)
    maxValue = max(values)

    min2Max[col] = (minValue, maxValue)

for i, row in patientData.iterrows():
    for col in columns:
        (minValue, maxValue) = min2Max[col]
        patientData.loc[i, col] = (row[col] - minValue) / (maxValue - minValue)

patientData

,患者ID,性别,年龄,省,民族,宗教信仰,学历,身高,体重,BMI指数,...,烟龄,平均每日吸烟次数,是否饮酒,平均每日饮酒次数,常饮酒类,锻炼频率,刷牙频率,重症等级,所属医院,所在病区
0,1688,1,0.744898,17,33,43,49,0.382353,0.148148,0.009615,...,0.000000,0.000000,93,0.90,96,0.1,0.526316,0.50,60,63
1,373,1,0.826531,16,33,43,50,0.352941,0.148148,0.019231,...,0.000000,0.000000,94,0.00,97,0.0,0.157895,0.50,59,62
2,2505,0,0.306122,2,33,43,53,0.411765,0.407407,0.500000,...,0.000000,0.000000,94,0.00,97,0.3,0.578947,0.75,60,64
3,1863,0,0.306122,4,33,43,53,0.352941,0.648148,1.000000,...,0.000000,0.000000,94,0.00,97,0.1,0.736842,0.50,60,64
4,1564,1,0.836735,18,33,43,50,0.500000,0.203704,0.038462,...,0.381579,0.400000,95,0.30,98,0.0,0.105263,1.00,60,63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,1050,1,0.265306,3,33,43,52,0.617647,0.388889,0.269231,...,0.157895,0.933333,95,0.70,100,0.5,0.894737,0.00,61,65
2496,1029,0,0.714286,5,34,43,49,0.382353,0.148148,0.009615,...,0.000000,0.000000,95,0.35,100,0.0,0.421053,0.25,61,65
2497,2467,0,0.295918,24,33,43,53,0.323529,0.388889,0.528846,...,0.000000,0.000000,94,0.00,97,0.3,0.736842,0.75,60,64
2498,1736,0,0.795918,3,33,43,49,0.058824,0.037037,0.028846,...,0.000000,0.000000,94,0.00,97,0.0,0.421053,1.00,60,63
2499,1169,0,0.418367,12,33,43,50,0.382353,0.648148,0.990385,...,0.000000,0.000000,94,0.00,97,0.1,0.842105,0.50,61,65

In [26]:
patientCount = 1000
similarity_matrix = [[0] * patientCount for _ in range(patientCount)]

for i in range(patientCount):
    for j in range(patientCount):
        res = getSimilarity(patientData.iloc[i][2:], patientData.iloc[j][2:])
        if res >= 0.9:
            similarity_matrix[i][j] = res
np.array(similarity_matrix)

,患者ID,性别,年龄,省,民族,宗教信仰,学历,身高,体重,BMI指数,...,烟龄,平均每日吸烟次数,是否饮酒,平均每日饮酒次数,常饮酒类,锻炼频率,刷牙频率,重症等级,所属医院,所在病区
0,1688,1,0.744898,0.500000,0.000000,0.0,0.0,0.382353,0.148148,0.009615,...,0.000000,0.000000,0.0,0.90,0.00,0.1,0.526316,0.50,0.5,0.090909
1,373,1,0.826531,0.466667,0.000000,0.0,0.2,0.352941,0.148148,0.019231,...,0.000000,0.000000,0.5,0.00,0.25,0.0,0.157895,0.50,0.0,0.000000
2,2505,0,0.306122,0.000000,0.000000,0.0,0.8,0.411765,0.407407,0.500000,...,0.000000,0.000000,0.5,0.00,0.25,0.3,0.578947,0.75,0.5,0.181818
3,1863,0,0.306122,0.066667,0.000000,0.0,0.8,0.352941,0.648148,1.000000,...,0.000000,0.000000,0.5,0.00,0.25,0.1,0.736842,0.50,0.5,0.181818
4,1564,1,0.836735,0.533333,0.000000,0.0,0.2,0.500000,0.203704,0.038462,...,0.381579,0.400000,1.0,0.30,0.50,0.0,0.105263,1.00,0.5,0.090909
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,1050,1,0.265306,0.033333,0.000000,0.0,0.6,0.617647,0.388889,0.269231,...,0.157895,0.933333,1.0,0.70,1.00,0.5,0.894737,0.00,1.0,0.272727
2496,1029,0,0.714286,0.100000,0.111111,0.0,0.0,0.382353,0.148148,0.009615,...,0.000000,0.000000,1.0,0.35,1.00,0.0,0.421053,0.25,1.0,0.272727
2497,2467,0,0.295918,0.733333,0.000000,0.0,0.8,0.323529,0.388889,0.528846,...,0.000000,0.000000,0.5,0.00,0.25,0.3,0.736842,0.75,0.5,0.181818
2498,1736,0,0.795918,0.033333,0.000000,0.0,0.0,0.058824,0.037037,0.028846,...,0.000000,0.000000,0.5,0.00,0.25,0.0,0.421053,1.00,0.5,0.090909
2499,1169,0,0.418367,0.333333,0.000000,0.0,0.2,0.382353,0.648148,0.990385,...,0.000000,0.000000,0.5,0.00,0.25,0.1,0.842105,0.50,1.0,0.272727

In [27]:
with open('simi_matrix_patient.txt', 'w') as file:
    for i in range(patientCount):
        similarity_info = ', '.join(map(str, similarity_matrix[i]))
        file.write(f'{i}: {similarity_info}\n')

array([[1.  , 0.72, 0.45, ..., 0.43, 0.43, 0.53],
       [0.72, 1.  , 0.5 , ..., 0.48, 0.49, 0.66],
       [0.45, 0.5 , 1.  , ..., 0.82, 0.87, 0.46],
       ...,
       [0.43, 0.48, 0.82, ..., 1.  , 0.83, 0.44],
       [0.43, 0.49, 0.87, ..., 0.83, 1.  , 0.44],
       [0.53, 0.66, 0.46, ..., 0.44, 0.44, 1.  ]])

In [28]:
k = 1
while k >= 0.8:
    edges = {}
    edgeCount = 0
    for i in range(patientCount):
        tarList = []
        for j in range(patientCount):
            if i != j:
                if similarity_matrix[i][j] >= k:
                    tarList.append(j)

        if len(tarList) > 0:
            edges[i] = tarList
            edgeCount += len(tarList)

    if edgeCount > 0:
        with open(f'edge/200_1000/edge_patient_{round(k, 1)}.txt', 'w') as file:
            for i in range(patientCount):
                if i in edges.keys():
                    edgeInfo = ', '.join(map(str, edges[i]))
                    file.write(f'{i}: {edgeInfo}\n')

            file.write(f'edgeCount: {edgeCount}\n')

    print(k, edgeCount)
    k -= 0.1

In [29]:
nurseData = pd.read_csv('normalized_nurseData.csv')
nurseData

0.9 1702
0.8 11286
0.7000000000000001 48530
0.6000000000000001 158836
0.5000000000000001 358046

In [49]:
min2Max = {}
columns = ['普通话程度', '方言程度']

for col in columns:
    values = nurseData[col].tolist()
    minValue = min(values)
    maxValue = max(values)

    min2Max[col] = (minValue, maxValue)

for i, row in nurseData.iterrows():
    for col in columns:
        (minValue, maxValue) = min2Max[col]
        nurseData.loc[i, col] = (row[col] - minValue) / (maxValue - minValue)

nurseData

,护工ID,护工姓名,性别,年龄,省,民族,宗教信仰,学历,普通话程度,方言程度,...,在岗时间,擅长科室,擅长科室种类,接单数,活跃度,评分,所属服务商,常驻医院,主要负责病区,其他负责病区
0,1641,王爱平,0,0.561224,2,33,43,49,0,0.0,...,0.780876,急诊科、泌尿科,0.50,0.153846,0.029762,0.4,JSMSJ,59,62,67
1,1725,孙桂梅,0,0.591837,2,33,43,50,1,1.0,...,0.772908,无,0.00,0.000000,0.011905,1.0,NBAX,60,63,74
2,1873,陈均妃,0,0.489796,2,33,43,49,0,0.5,...,0.741036,泌尿科,0.25,0.076923,0.011905,0.4,JSMSJ,59,62,67
3,6195,李婷,0,0.479592,2,33,43,51,1,1.0,...,0.049801,无,0.00,0.076923,0.125000,1.0,NBAX,60,64,74
4,4450,董建敏,0,0.448980,3,33,43,49,0,1.0,...,0.521912,无,0.00,0.000000,0.005952,0.4,NBAX,60,63,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,5461,邹生凤,0,0.540816,4,33,43,52,1,1.0,...,0.213147,无,0.00,0.000000,0.011905,0.8,JSMSJ,59,67,74
496,5074,王艳慧,0,0.387755,2,33,43,50,1,0.5,...,0.394422,无,0.00,0.769231,0.125000,0.2,NBAX,60,64,63
497,1518,徐月仙,0,0.602041,2,33,43,49,0,0.5,...,0.780876,无,0.00,0.000000,0.005952,0.4,JSMSJ,61,65,74
498,5499,张红英,0,0.510204,2,33,43,51,0,0.0,...,0.199203,无,0.00,0.153846,0.095238,0.0,SHZF,61,66,74
499,1506,贺远娥,0,0.510204,2,33,43,51,0,0.0,...,0.780876,无,0.00,0.307692,0.023810,0.4,JSMSJ,61,65,70

In [50]:
nurseData = nurseData.drop('擅长科室', axis=1)
nurseData = nurseData.drop('所属服务商', axis=1)
nurseData

,护工ID,护工姓名,性别,年龄,省,民族,宗教信仰,学历,普通话程度,方言程度,...,BMI指数,体型,在岗时间,擅长科室种类,接单数,活跃度,评分,常驻医院,主要负责病区,其他负责病区
0,1641,王爱平,0,0.561224,2,33,43,49,0,0.0,...,0.326923,55,0.780876,0.50,0.153846,0.029762,0.4,59,62,67
1,1725,孙桂梅,0,0.591837,2,33,43,50,1,1.0,...,0.250000,55,0.772908,0.00,0.000000,0.011905,1.0,60,63,74
2,1873,陈均妃,0,0.489796,2,33,43,49,0,0.5,...,0.730769,56,0.741036,0.25,0.076923,0.011905,0.4,59,62,67
3,6195,李婷,0,0.479592,2,33,43,51,1,1.0,...,0.317308,55,0.049801,0.00,0.076923,0.125000,1.0,60,64,74
4,4450,董建敏,0,0.448980,3,33,43,49,0,1.0,...,0.038462,57,0.521912,0.00,0.000000,0.005952,0.4,60,63,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,5461,邹生凤,0,0.540816,4,33,43,52,1,1.0,...,0.423077,55,0.213147,0.00,0.000000,0.011905,0.8,59,67,74
496,5074,王艳慧,0,0.387755,2,33,43,50,1,0.5,...,0.028846,57,0.394422,0.00,0.769231,0.125000,0.2,60,64,63
497,1518,徐月仙,0,0.602041,2,33,43,49,0,0.5,...,0.000000,57,0.780876,0.00,0.000000,0.005952,0.4,61,65,74
498,5499,张红英,0,0.510204,2,33,43,51,0,0.0,...,0.288462,55,0.199203,0.00,0.153846,0.095238,0.0,61,66,74
499,1506,贺远娥,0,0.510204,2,33,43,51,0,0.0,...,0.019231,57,0.780876,0.00,0.307692,0.023810,0.4,61,65,70

In [51]:
nurseData.to_csv('nurseData.csv', index=False)